version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - redis
    ports:
      - '8080:80'
    tty: true
    container_name: node_app
    volumes:
      - ./app:/app

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./data/redis:/data
    container_name: redis
